---
- name: GitHub Actions Runner
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml  

  tasks:
    - include_role:
        name: monolithprojects.github_actions_runner
      vars:
        github_repo: "{{ repo }}"
        runner_labels: "{{ labels }}"
        runner_version: "{{ runnerversion }}"
        runner_name: "{{ runnername }}"
        runner_user: "{{ runneruser }}"
        runner_dir: "{{ runnerdir }}"
        all_runners_in_same_repo: "{{ runners_in_same_repo }}" # Set to false when provisioning runners for more than one repository within single play
        github_account: "{{ githubaccount }}"
        access_token: "{{ pat }}"
        runner_state: "{{ state }}"
        reinstall_runner: "{{ reinstallrunner }}"